### ISSUE TITLE
Let players disable AI filling

### ISSUE THREAD

**Issue by kraktus** [JohnChernoff/MoleChess#8]
We were slowly waiting for players to join, but when we reached 3 the game started, filled with 3 bots.

Could be a mistake on our part by clicking on "start" to early, but having an explicit mention/option would be nice.

Cheers

**Comment by JohnChernoff** [comment]
"Start" does indeed start the game which requires at least three players on each side, and all joining occurs before that point.   Perhaps a pop-up could appear if you start a game with less than the required number to confirm that you wish to begin with some bots added?

**Comment by kraktus** [comment]
would be perfect
